FROM alpine:latest

RUN apk add --no-cache git go

ARG CONSUMER_KEY=""
ARG CONSUMER_SECRET=""
ARG ACCESS_TOKEN=""
ARG ACCESS_SECRET=""

ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH
ENV CONSUMER_KEY=$CONSUMER_KEY
ENV CONSUMER_SECRET=$CONSUMER_SECRET
ENV ACCESS_TOKEN=$ACCESS_TOKEN
ENV ACCESS_SECRET=$ACCESS_SECRET

WORKDIR /go/src/twitter-bot
COPY . .
RUN cp twitter-upload /usr/local/bin
ENV GO111MODULE=on
RUN go build .
CMD [ "./twitter-bot-test" ]
