FROM alpine:latest

RUN apk add --no-cache git go

ARG BEARER_TOKEN=""
ARG MONGO_URI=""
ARG DATABASE_NAME=""
ARG COLLECTION_NAME=""

ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH
ENV BEARER_TOKEN=$BEARER_TOKEN
ENV MONGO_URI=$MONGO_URI
ENV DATABASE_NAME=$DATABASE_NAME
ENV COLLECTION_NAME=$COLLECTION_NAME

WORKDIR /go/src/stitch-it
COPY . .
ENV GO111MODULE=on
RUN go build .
CMD [ "./stitch-it" ]
